config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :my_profile]

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  get 'mailbox/inbox', to: 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent', to: 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash', to: 'mailbox#trash', as: :mailbox_trash

  # Root
  root 'pages#home'

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get '/log_in', to: 'devise/sessions#new'
  end

  get '/my_profile', to: 'users#my_profile'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :mailbox, :conversation

  private
  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to root_path
  end

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message has been sent successfully."
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user).order("created_at ASC")
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:success] = 'Reply sent.'
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation has been moved to the trash.'
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    flash[:success] = 'The conversation has been restored.'
    redirect_to mailbox_inbox_path
  end

  def empty_trash
    current_user.mark_as_deleted(mailbox.trash.to_a)
    redirect_to mailbox_trash_path
  end

  private
  def conversation_params
    params.require(:conversation).permit(:subject, :body, recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 20)
    else
      redirect_to '/', alert: 'You are not allowed to do this.'
    end
  end

  def my_profile
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

  def flash_class(level)
    case level.to_sym
      when :success then "alert alert-success"
      when :notice then "alert alert-success"
      when :info then "alert alert-info"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    mailbox.inbox(unread: true).count
  end

  def unread_messages
    mailbox.inbox(unread: true).present?
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<% if conversation.is_unread?(current_user) %>
  <div class="conversation-body-unread">
<% else %>
  <div class="conversation-body">
<% end %>
  <p><b>From: </b><%= conversation.originator.name %><br>
  <b>Participants: </b><% conversation.recipients.each do |recipient| %><%= recipient.name %><%= ", " unless recipient == conversation.recipients.last %><% end %><br>
  <b>Subject: </b><%= conversation.subject %><br>
  <b>Date: </b><i><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></i></p>
  
  <% if conversation.is_trashed?(current_user) %>
    <%= link_to 'Restore', untrash_conversation_path(conversation), class: 'btn btn-sm btn-info pull-right', method: :post %>
  <% else %>
    <%= link_to "View Message", conversation_path(conversation), class: 'btn btn-sm btn-custom pull-right' %>
  <% end %>

  <p><%= truncate conversation.messages.last.body, length: 50 %></p>
  <hr class="hr-small">
</div>

app/views/conversations/_form.html.erb
<div class="new-message">

  <%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: 'chosen-select form-control' })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, rows: 5, placeholder: "Message", class: 'form-control no-resize', required: true  %>
    </div>

    <%= f.submit "Send", class: 'btn btn-md btn-custom' %>

  <% end %>

</div>

app/views/conversations/_messages.html.erb
<h2>Conversation</h2>

<br>

<h4><b>Participants: </b><% conversation.recipients.each do |recipient| %><%= recipient.name %><%= ", " unless recipient == conversation.recipients.last %><% end %><br>
<b>Subject: </b><%= conversation.subject %></h4>

<hr class="hr-big">

<h3>Messages</h3>

<% @receipts.each do |receipt| %>
  <% message = receipt.message %>

  <div class="message-body">
    <p><small><b>From: </b><%= message.sender.name %><br>
    <b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small><p>
    <p><%= message.body %></p>
    <hr class="hr-small">
  </div>

<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="container">

  <h2>Conversation Subject: <%= conversation.subject %></h2>

  <div class="row">
    <div class="col-md-12">
      <%= link_to "New Message", new_conversation_path, class: 'btn btn-md btn-custom' %>
    </div>
    <br>
    <br>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render 'mailbox/folders' %>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">

          <div class="pull-right">
            <% if conversation.is_trashed?(current_user) == false %>
              <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-sm btn-danger', method: :post, data: {confirm: 'Are you sure?'} %>
            <% end %>
          </div>
          <div>
            <%= render partial: 'messages' %>
          </div>
        </div>

        <div class="panel panel-footer">
          <!-- Reply form -->
          <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, rows: 5, class: 'form-control no-resize', placeholder: 'Reply', required: true %>
            </div>
            <%= f.submit "Send", class: 'btn btn-md btn-custom' %>
          <% end %>
        </div>
      </div>
    </div>

  </div><!-- end of .row -->

</div><!-- end of .container -->

<div class="extra-space"></div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">

      <div class="copyright">
        <p>Coded by Hand.<br>
        &copy; 2016, Christian McTighe.</p>
      </div>

    </div><!-- end of row -->
  </div><!-- end of container-fluid -->

</footer>

app/views/layouts/_head.html.erb
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Christian McTighe">
    <title>Mountain Mail</title>

    <!-- Fonts -->
    <!-- Google Fonts Link Here -->
    <script src="https://use.fontawesome.com/981382a342.js"></script>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-nav-bar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Mountain Mail", root_path, class: "navbar-brand") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="top-nav-bar">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', '/my_profile', class: "scroll-nav" %></li>
          <li><%= link_to 'See Users', users_path %></li>
          <% if unread_messages %>
            <li><%= link_to "Messages (#{unread_messages_count})", mailbox_inbox_path, class: "scroll-nav", id: "bold" %></li>
          <% else %>
            <li><%= link_to "Messages", mailbox_inbox_path, class: "scroll-nav" %></li>
          <% end %>
          <li><%= link_to "Log Out (#{current_user.name})", destroy_user_session_path, method: :delete, class: "scroll-nav" %></li>
        <% else %>
          <li><%= link_to "Sign Up", '/sign_up', class: "scroll-nav" %></li>
          <li><%= link_to "Log In", '/log_in', class: "scroll-nav" %></li>
        <% end %>
      </ul>
    </div><!-- .navbar-collapse -->

  </div><!-- .container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/head' %>

  <body>

    <%= render 'layouts/nav' %>

    <% flash.each do |key, value| %>
      <div class="text-center <%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/mailbox/_folder_view.html.erb
<div class="container">

  <h2>Your Mail</h2>

  <br>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "New Message", new_conversation_path, class: "btn btn-md btn-custom" %>
    </div>
    <br>
    <br>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render 'mailbox/folders' %>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if is_conversation %>
            <%= render 'conversations/form' %>
          <% else %>
            <% if messages.present? %>
              <%= render partial: 'conversations/conversation', collection: messages %>
            <% else %>
              <p>No messages.</p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>

  <div class="pull-right">
    <% if @trash.present? %>
      <%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-md btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>

</div>

<div class="extra-space"></div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
      <span class="label label-danger pull-right"><%= unread_messages_count %></span>
      <em class="fa fa-inbox fa-lg"></em>
      <span>Inbox</span>
    <% end %>
  </li>

  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>
      <em class="fa fa-paper-plane-o fa-lg"></em>
      <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
      <em class="fa fa-trash-o fa-lg"></em>
      <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>

app/views/pages/home.html.erb
<section class="jumbotron">
  <div class="container-fluid">

    <div>
      <h1>Mountain Mail</h1>
      <br>
      <h2><i>E-mail like you've never seen before</i></h2>
      <br>
      <p>
        <% if user_signed_in? %>
          <%= link_to 'New Message', new_conversation_path, class: "btn btn-custom btn-lg" %>
          <%= link_to 'Messages', mailbox_inbox_path, class: "btn btn-custom btn-lg" %>
        <% else %>
          <%= link_to("Sign Up", '/sign_up', class: "btn btn-custom btn-lg") %>
          <%= link_to("Log In", '/log_in', class: "btn btn-custom btn-lg") %>
        <% end %>
      </p>
    </div>

  </div><!-- end of container -->
</section>

<!-- Lower Section -->
<section class="lower-section">
  <div class="container">

    <% if user_signed_in? %>
      <h2>Welcome back, <%= current_user.name %>!</h2>
      <br>
      <h2>Please let us know if you have<br>
      any feedback or other comments.</h2>

    <% else %>
      <h2>We take messaging to new heights.</h2>

      <h2>The latest, most modern, up-to-date way to send mail.</h2>

      <h2>Try it out, you won't be disappointed.</h2>

      <h2>Guaranteed.</h2>
    <% end %>

    <div class="row" id="icon-row">
      <div class="col-xs-2 col-xs-offset-3">
        <div class="icon-box">
          <span class="fa fa-fighter-jet fa-3x"></span>
          <p>Fast</p>
        </div>
      </div>

      <div class="col-xs-2">
        <div class="icon-box">
          <span class="fa fa-life-ring fa-3x"></span>
          <p>Secure</p>
        </div>
      </div>

      <div class="col-xs-2">
        <div class="icon-box">
          <span class="fa fa-thumbs-o-up fa-3x"></span>
          <p>Easy</p>
        </div>
      </div>

    </div><!-- end of .row -->

  </div><!-- end of container -->
</section>

app/views/users/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-sm-6">
      <br>
      <%= image_tag("mountains2.jpg", class: "img-responsive", id: "users-mountain-pic") %>
    </div>

    <div class="col-sm-6">

      <h2>Mountain Mail Users</h2>
      <br>

      <p>Here is a list of all of our registered users.<br>
      <i>Please remember to follow the site's guidelines, when sending other users a message.</i></p>
      <br>

      <div class="row">
        <% @users.each do |user| %>
          <div class="col-md-4 col-xs-6">
            <div class="user-box">
              <% if current_user == user %>
                <%= user.name %> (You)
                <br>
                <%= link_to 'Send message', new_conversation_path(to: user.id), class: 'btn btn-xs btn-custom disabled' %>
              <% else %>
                <%= user.name %>
                <br>
                <%= link_to 'Send message', new_conversation_path(to: user.id), class: 'btn btn-xs btn-custom' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <%= will_paginate %>

    </div><!-- end of .col-md-6 -->
  </div><!-- end of .row -->

</div>

<div class="extra-space"></div>

app/views/users/my_profile.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-6">
      <br>
      <%= image_tag("mountains3.jpg", class: "img-responsive", id: "profile-mountain-pic") %>
    </div>

    <div class="col-sm-6">

      <h2>My Profile</h2>
      <br>
      <p><b>Name:</b>
      <%= @user.name %></p>
      <p><b>Email:</b>
      <%= @user.email %></p>
      <p><b>Member Since:</b>
      <%= @user.created_at.strftime("%B %e, %Y") %></p>
      <br>
      <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-md btn-custom" %>
    </div>

  </div><!-- end of .row -->
</div><!-- end of .container -->

<div class="extra-space"></div>